name: "Run Tests"
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.4.1
            - name: Install dependencies
              run: npm install 
            - name: "Run Tests"
              run: npm run test


